[theme]
primaryColor = "#4F8BF9"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

[server]
headless = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
